### ISSUE TITLE
[Feature request] Provide option to disable eslint format (e.g. stylistic)

### ISSUE THREAD

**Issue by Innei** [hyoban/eslint-config-hyoban#56]
### Clear and concise description of the problem

Thanks for the open source eslint config, I would love to use your config, but I don't want to use eslint's format, so I suggest the add option to disable format.

### Suggested solution

```ts
 defineConfig(
  {
    stylistic: false
  },
}
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/hyoban/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/hyoban/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hyoban** [comment]
OK, will do it tonight.
